// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoi1DinHFe1x69ekIN8eoK-zzzk0EBVLs',
    appId: '1:533168620057:web:373399c830b1bf294c6088',
    messagingSenderId: '533168620057',
    projectId: 'egycan-arabian-market-827df',
    authDomain: 'egycan-arabian-market-827df.firebaseapp.com',
    storageBucket: 'egycan-arabian-market-827df.appspot.com',
    measurementId: 'G-CTFJDJJQQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChQ7LyS7t3Bv6-eq4CKIAAJJIcFjTI_5k',
    appId: '1:533168620057:android:cd6d04a2c73a5dc44c6088',
    messagingSenderId: '533168620057',
    projectId: 'egycan-arabian-market-827df',
    storageBucket: 'egycan-arabian-market-827df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBypDInv-4Sl7b6wPioaZfGBum-mO1c1bU',
    appId: '1:533168620057:ios:7cfdfb05c2506b804c6088',
    messagingSenderId: '533168620057',
    projectId: 'egycan-arabian-market-827df',
    storageBucket: 'egycan-arabian-market-827df.appspot.com',
    iosBundleId: 'com.example.egycanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBypDInv-4Sl7b6wPioaZfGBum-mO1c1bU',
    appId: '1:533168620057:ios:7cfdfb05c2506b804c6088',
    messagingSenderId: '533168620057',
    projectId: 'egycan-arabian-market-827df',
    storageBucket: 'egycan-arabian-market-827df.appspot.com',
    iosBundleId: 'com.example.egycanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoi1DinHFe1x69ekIN8eoK-zzzk0EBVLs',
    appId: '1:533168620057:web:a5a12bf436f9fad04c6088',
    messagingSenderId: '533168620057',
    projectId: 'egycan-arabian-market-827df',
    authDomain: 'egycan-arabian-market-827df.firebaseapp.com',
    storageBucket: 'egycan-arabian-market-827df.appspot.com',
    measurementId: 'G-YYBQZD5K6T',
  );
}
